// Code generated by protoc-gen-go. DO NOT EDIT.
// source: arith.proto

/*
Package pb is a generated protocol buffer package.

生成的程式在 Golang 中將會屬於 `pb` 套件。

It is generated from these files:
	arith.proto

It has these top-level messages:
	CalcRequest
	CalcReply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// CalcRequest 包含了兩個數字，將會傳送至計算服務並對兩個數字進行計算。
type CalcRequest struct {
	NumberA int32 `protobuf:"varint,1,opt,name=number_a,json=numberA" json:"number_a,omitempty"`
	NumberB int32 `protobuf:"varint,2,opt,name=number_b,json=numberB" json:"number_b,omitempty"`
}

func (m *CalcRequest) Reset()                    { *m = CalcRequest{} }
func (m *CalcRequest) String() string            { return proto.CompactTextString(m) }
func (*CalcRequest) ProtoMessage()               {}
func (*CalcRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CalcRequest) GetNumberA() int32 {
	if m != nil {
		return m.NumberA
	}
	return 0
}

func (m *CalcRequest) GetNumberB() int32 {
	if m != nil {
		return m.NumberB
	}
	return 0
}

// CalcReply 是計算結果，將會回傳給客戶端。
type CalcReply struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *CalcReply) Reset()                    { *m = CalcReply{} }
func (m *CalcReply) String() string            { return proto.CompactTextString(m) }
func (*CalcReply) ProtoMessage()               {}
func (*CalcReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CalcReply) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*CalcRequest)(nil), "pb.CalcRequest")
	proto.RegisterType((*CalcReply)(nil), "pb.CalcReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Calculator service

type CalculatorClient interface {
	// Plus 會接收 CalcRequest 資料作加總，最終會回傳 CalcReply。
	Plus(ctx context.Context, in *CalcRequest, opts ...grpc.CallOption) (*CalcReply, error)
}

type calculatorClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorClient(cc *grpc.ClientConn) CalculatorClient {
	return &calculatorClient{cc}
}

func (c *calculatorClient) Plus(ctx context.Context, in *CalcRequest, opts ...grpc.CallOption) (*CalcReply, error) {
	out := new(CalcReply)
	err := grpc.Invoke(ctx, "/pb.Calculator/Plus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Calculator service

type CalculatorServer interface {
	// Plus 會接收 CalcRequest 資料作加總，最終會回傳 CalcReply。
	Plus(context.Context, *CalcRequest) (*CalcReply, error)
}

func RegisterCalculatorServer(s *grpc.Server, srv CalculatorServer) {
	s.RegisterService(&_Calculator_serviceDesc, srv)
}

func _Calculator_Plus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Plus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Calculator/Plus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Plus(ctx, req.(*CalcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Calculator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Calculator",
	HandlerType: (*CalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Plus",
			Handler:    _Calculator_Plus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arith.proto",
}

func init() { proto.RegisterFile("arith.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2c, 0xca, 0x2c,
	0xc9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x72, 0xe6, 0xe2, 0x76,
	0x4e, 0xcc, 0x49, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe4, 0xe2, 0xc8, 0x2b,
	0xcd, 0x4d, 0x4a, 0x2d, 0x8a, 0x4f, 0x94, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x62, 0x87, 0xf0,
	0x1d, 0x91, 0xa4, 0x92, 0x24, 0x98, 0x90, 0xa5, 0x9c, 0x94, 0x94, 0xb9, 0x38, 0x21, 0x86, 0x14,
	0xe4, 0x54, 0x0a, 0x89, 0x71, 0xb1, 0x15, 0xa5, 0x16, 0x97, 0xe6, 0x94, 0x40, 0x0d, 0x80, 0xf2,
	0x8c, 0xcc, 0xb8, 0xb8, 0x40, 0x8a, 0x4a, 0x73, 0x12, 0x4b, 0xf2, 0x8b, 0x84, 0x34, 0xb8, 0x58,
	0x02, 0x72, 0x4a, 0x8b, 0x85, 0xf8, 0xf5, 0x0a, 0x92, 0xf4, 0x90, 0x5c, 0x20, 0xc5, 0x8b, 0x10,
	0x28, 0xc8, 0xa9, 0x54, 0x62, 0x48, 0x62, 0x03, 0x3b, 0xd6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0xb8, 0xe4, 0x8d, 0xf1, 0xbb, 0x00, 0x00, 0x00,
}
